### ISSUE TITLE
Update Doctrine/Cache Requirement to v1.4.*

### ISSUE THREAD

**Issue by mandersondesign** [giantbomb/giantbomb-php-api#2]
Hi,

I would really love to use your php sdk, but it requires doctrine/cache v1.3.\* only. As of Laravel 4.1, doctrine v.1.4.\* comes standard with that framework, causing this problem when trying to update composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for giantbomb/giantbomb-php-api dev-master -> satisfiable by giantbomb/giantbomb-php-api[dev-master].
    - giantbomb/giantbomb-php-api dev-master requires doctrine/cache 1.3.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

Could you update your requirements for this? I can do a pull request if that would be easier?

Thanks.

**Comment by cryptiklemur** [comment]
@mandersondesign yeah, go ahead and make a PR, so you can test it and make sure it works, ill merge it in if it looks good :)

**Comment by cryptiklemur** [comment]
Super bump, @mandersondesign doctrine/cache 1.4 is under the dev stability requirement, and i'm not comfortable with it there.

Laravel shouldn't be using a dev stability repo, and I would suggest you open up a bug request there, if you still need this.
