### ISSUE TITLE
Getting Games for a particular Genre

### ISSUE THREAD

**Issue by Purus** [giantbomb/giantbomb-php-api#3]
How can I get all games for a particular genre? I could not find any documentation or filter for it.

**Comment by cryptiklemur** [comment]
similar to https://github.com/giantbomb/giantbomb-php-api/issues/4

**Comment by Purus** [comment]
The below filter does not work. It list all games.

``` php
        $requestArgs = array(
            'limit' => $count,
            'offset' => $page,
            'filter' => 'genres:' . $genreId,
        );
```

**Comment by Purus** [comment]
Can someone confirm if this is really possible?

**Comment by cryptiklemur** [comment]
Check the API docs. I'm literally just wrapping the api

**Comment by Purus** [comment]
FYI - Its not supported in the API.
