### ISSUE TITLE
Getting Games for a particular Platform

### ISSUE THREAD

**Issue by Purus** [giantbomb/giantbomb-php-api#4]
I see that there is a filter for getting games for a particular platform.

I am not sure how to use that. Below is the code I have used. But it does not list the games for the platform.

``` php
        $requestArgs = array(
            'limit' => $count,
            'offset' => $page,
            'platforms' => $platformId,
        );

        $response = $this->client->getGames($requestArgs);
```

What should I do make this work?

**Comment by cryptiklemur** [comment]
More a question for giantbomb, but, i can answer it either way. Same for your other ticket:

``` php
$response = $this->giantBomb->getGames(['filter' => 'platforms:'.$id]);
```

**Comment by Purus** [comment]
So I believe, the documentation at http://www.giantbomb.com/api/documentation#toc-0-15 is wrong which says it has "platforms" filter.

Thanks for your tip.
